[package]
name = "zigbee-ui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "zigbee-analyzer"
path = "src/main.rs"

[dependencies]
zigbee-core = { workspace = true }
zigbee-hal = { workspace = true }
zigbee-drivers = { workspace = true }
zigbee-analysis = { workspace = true }

tokio = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }