[package]
name = "zigbee-analysis"
version.workspace = true
edition.workspace = true

[dependencies]
zigbee-core = { path = "../zigbee-core" }
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true