[package]
name = "zigbee-drivers"
version.workspace = true
edition.workspace = true

[dependencies]
zigbee-core = { path = "../zigbee-core" }
zigbee-hal = { path = "../zigbee-hal" }
serialport.workspace = true
rusb.workspace = true
thiserror.workspace = true
pcap-file = "2.0"  # For PCAP reading