[package]
name = "zigbee-drivers"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
zigbee-core = { workspace = true }
zigbee-hal = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
serialport = { workspace = true }
rusb = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }